#!/bin/sh
code --install-extension DotJoshJohnson.xml
code --install-extension HookyQR.beautify
code --install-extension PeterJausovec.vscode-docker
code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension dcr30.lualinter
code --install-extension djabraham.vscode-yaml-validation
code --install-extension donjayamanne.python
code --install-extension itryapitsin.Scala
code --install-extension lukehoban.Go
code --install-extension magicstack.MagicPython
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mitaki28.vscode-clang
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ravilang.ravi-debug
code --install-extension robertohuertasm.vscode-icons
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
