export let restaurantlist = [
  {
    name: "용인 가람오리로스",
    glyphicons: "bi-star",
    tags: "오리 돌판 구이",
    review: "https://maps.app.goo.gl/TsLdezRvU9hvBeq28",
  },
  {
    name: "용인 Lamir",
    glyphicons: "bi-star",
    tags: "빵, 카페, 디저트",
    review: "https://maps.app.goo.gl/9dcuZc3R6otRGQi26",
  },
  {
    name: "종로 두오모",
    glyphicons: "bi-star",
    tags: "파스타, 이탈리아음식",
    review: "https://maps.app.goo.gl/PmcrVjbCsYxXduPMA",
  },
  {
    name: "청국장과 보리밥",
    glyphicons: "bi-star",
    tags: "청국장, 보리밥",
    review: "https://maps.app.goo.gl/5UNzAcyt29iyYnxP7",
  },
  {
    name: "홍익돈까스 춘천점",
    glyphicons: "bi-star",
    tags: "왕 돈까스, 크림파스타, 볶음 우동",
    review: "https://maps.app.goo.gl/rB8FYjj1qfeM5Sxt6",
  },
  {
    name: "양구 담스포",
    glyphicons: "bi-star",
    tags: "쌀국수",
    review: "https://maps.app.goo.gl/TkJRJFhVGDHjaxfTA",
  },
  {
    name: "양구 아이쇼야",
    glyphicons: "bi-star",
    tags: "라멘",
    review: "https://maps.app.goo.gl/k7RLHSAayNjfUMvx7",
  },
  {
    name: "디저트39 판교역점",
    glyphicons: "bi-star",
    tags: "빵, 카페, 디저트",
    review: "https://maps.app.goo.gl/4GhJw9XtcoZG7Fhg8",
  },
  {
    name: "운중동 Artique(아티크)",
    glyphicons: "bi-star",
    tags: "빵, 카페, 디저트",
    review: "https://maps.app.goo.gl/mQ3aojG9pbNYZUjh9",
  },
  {
    name: "운중동 능이향기",
    glyphicons: "bi-star",
    tags: "오리백숙,닭 도리탕,닭백숙",
    review: "https://maps.app.goo.gl/7MKb1NQraLKmmkz39",
  },
  {
    name: "AU BON BEURRE",
    glyphicons: "bi-star",
    tags: "소금빵,  바게트",
    review: "https://maps.app.goo.gl/FHR8UF181LmmX8eU6",
  },
  {
    name: "꾸아 광교점",
    glyphicons: "bi-star",
    tags: "비빔국수, 쌀국수",
    review: "https://maps.app.goo.gl/mfE3uE3MjBrr7dKh7",
  },
  {
    name: "마루심",
    glyphicons: "bi-star",
    tags: "장어덮밥",
    review: "https://maps.app.goo.gl/qgYHGwSv19s8saMA9",
  },
  {
    name: "양재 정글 바베큐",
    glyphicons: "bi-star",
    tags: "돼지고기 바베큐, 라면, 과자",
    review: "https://maps.app.goo.gl/pdT5ru1A2SAnvW8eA",
  },
  {
    name: "용인 고기리막국수",
    glyphicons: "bi-heart",
    tags: "들기름 막국수, 물/비냉 막국수",
    review: "https://maps.app.goo.gl/CLdH3K2nFfpW55WT6",
  },
  {
    name: "판교 네코부루",
    glyphicons: "bi-star",
    tags: "돈까스,카레우동,카레돌솥밥,메밀소바",
    review: "https://maps.app.goo.gl/xzAJvrFtcZcAzyzf7",
  },
  {
    name: "아비뉴파랑 후라토식당",
    glyphicons: "bi-star",
    tags: "돈까스",
    review: "https://maps.app.goo.gl/FKGhxCddHySxpQF57",
  },
  {
    name: "덕후선생 판교아비뉴프랑",
    glyphicons: "bi-star",
    tags: "북경오리,베이징덕",
    review: "https://maps.app.goo.gl/7yMUQ5P2y4Vko3Tk9",
  },
  {
    name: "서현 서울감자탕 정자점",
    glyphicons: "bi-star",
    tags: "감자탕",
  },
  {
    name: "아티제 판교알파리움점",
    glyphicons: "bi-star",
    tags: "카페",
    review: "https://maps.app.goo.gl/yghFyDCLqAUXpQZ29",
  },
  {
    name: "정자 최가돈까스",
    glyphicons: "bi-star",
    tags: "돈까스",
  },
  {
    name: "서현 화수목 샤브샤브",
    glyphicons: "bi-star",
    tags: "샤브샤브",
    review: "https://maps.app.goo.gl/6cV6wjn4QqpD5HZK6",
  },
  {
    name: "분당 구미동 야마다야",
    glyphicons: "bi-star",
    tags: "수타 우동,튀김",
  },
  {
    name: "판교 칠리셔스",
    glyphicons: "bi-star",
    tags: "칠리도그,칠리라이스,맥엔치즈프라이",
  },
  {
    name: "판교 다연",
    glyphicons: "bi-star",
    tags: "제육쌈밥",
  },
  {
    name: "판교 커먼치킨",
    glyphicons: "bi-star",
    tags: "함박 정식",
    review: "https://maps.app.goo.gl/1KfC5EJh8oTgqVNy5",
  },
  {
    name: "판교 라디오베이",
    glyphicons: "bi-star",
    tags: "파스타,피자,콥샐러드",
    review: "https://maps.app.goo.gl/8tSRdmVwHDHVHybB6",
  },
  {
    name: "판교 감성타코",
    glyphicons: "bi-heart",
    tags: "타코,멕시칸요리",
    review: "https://maps.app.goo.gl/6xo5yBGUSTMoEVzb6",
  },
  {
    name: "신승반점 현대백화점판교점",
    glyphicons: "bi-heart",
    tags: "유니짜장,짬뽕,탕수육",
  },
  {
    name: "이터스 현대백화점판교점",
    glyphicons: "bi-heart",
    tags: "칠리치킨타코,치킨퀘사디아",
    review: "https://maps.app.goo.gl/5GCg8mgPVcW4mBKB6",
  },
  {
    name: "운중동 춘천명물닭갈비",
    glyphicons: "bi-heart",
    tags: "닭갈비",
    review: "https://maps.app.goo.gl/MdENfWxXkq8RWUuw8",
  },
  {
    name: "판교 숙성도",
    glyphicons: "bi-heart",
    tags: "숙성 돼지고기,동치미국수,된장술밥",
    review: "https://maps.app.goo.gl/awDmVrMgbz3a5nyp8",
  },
  {
    name: "판교 우테이블",
    glyphicons: "bi-heart",
    tags: "소고기구이",
  },
  {
    name: "판교 Bientoi(비앙또아)",
    glyphicons: "bi-heart",
    tags: "오일파스타,오일샌드위치,스튜,브런치",
  },
  {
    name: "와플대학 분당정자캠퍼스",
    glyphicons: "bi-star",
    tags: "와플, 주스, 쉐이크",
    review: "https://maps.app.goo.gl/oNSereFJ4wYwEdR99",
  },
  {
    name: "정자 봄날에 청국장",
    glyphicons: "bi-star",
    tags: "보리밥",
    review: "https://maps.app.goo.gl/mRPCAp4LXWTd1qhj7",
  },
  {
    name: "보릿골 강동점",
    glyphicons: "bi-star",
    tags: "보리밥",
    review: "https://maps.app.goo.gl/e3KbCkbhGgYVXEWS8",
  },
  {
    name: "남양주 고향가는길",
    glyphicons: "bi-star",
    tags: "보리밥",
    review: "https://maps.app.goo.gl/FQ2oWPDaziEJhEw7A",
  },
  {
    name: "판교 붓처스컷",
    glyphicons: "bi-star",
    tags: "스테이크,아메리칸브런치",
  },
  {
    name: "정자 grado",
    glyphicons: "bi-star",
    tags: "파스타",
    review: "https://maps.app.goo.gl/bCgo3YXVRmyFvs7w8",
  },
  {
    name: "정자 bellra rosa",
    glyphicons: "bi-star",
    tags: "파스타",
    review: "https://maps.app.goo.gl/fvpKpmpwYBtGhBrw8",
  },
  {
    name: "정자 코이라멘",
    glyphicons: "bi-star",
    tags: "라멘,치킨가라아게,차슈덮밥",
    review: "https://maps.app.goo.gl/mqyA8YerbBffHAX69",
  },
  {
    name: "본설렁탕",
    glyphicons: "bi-star",
    tags: "홍설면,홍설렁탕,백설면,백설렁탕",
  },
  {
    name: "판교 담솥",
    glyphicons: "bi-star",
    tags: "가지솥밥",
  },
  {
    name: "일면식",
    glyphicons: "bi-star",
    tags: "칼국수,오징어덮밥,낚지볶음",
  },
  {
    name: "빕스",
    glyphicons: "bi-star",
    tags: "패밀리레스토랑",
  },
  {
    name: "판교 양육점",
    glyphicons: "bi-star",
    tags: "북해도식 양갈비 화로구이",
  },
  {
    name: "판교 매일식당",
    glyphicons: "bi-heart",
    tags: "수제돈까스",
  },
  {
    name: "인디테이블",
    glyphicons: "bi-star",
    tags: "치킨,커리",
  },
  {
    name: "판교 만복 국수",
    glyphicons: "bi-heart",
    tags: "비빔국수, 주먹밥",
  },
  {
    name: "미정 국수",
    glyphicons: "bi-star",
    tags: "비빔국수, 닭조림 덮밥",
  },
  {
    name: "판교 소바니 우동",
    glyphicons: "bi-star",
    tags: "돈까스, 생선까스, 우동, 김치알밥",
  },
  {
    name: "판교 이태원 천상",
    glyphicons: "bi-star",
    tags: "소바니 우동, 카레 우동",
  },
  {
    name: "판교 미래에셋 구내식당",
    glyphicons: "bi-heart",
    tags: "백반(4,500원, A/B코스 둘다 먹을수 있음)",
  },
  {
    name: "운중동 댓짱돈까스",
    glyphicons: "bi-heart",
    tags: "돈까스",
    review: "https://maps.app.goo.gl/DGqLPxFbvrwF18NW6",
  },
  {
    name: "위례 집나간 고등어",
    glyphicons: "bi-heart",
    tags: "고등어 구이",
    review: "https://maps.app.goo.gl/U1CoWMaWZ8fpZ2LH7",
  },
  {
    name: "판교 스마일쿡",
    glyphicons: "bi-heart",
    tags: "백반(6천원, 현금 쿠폰구입시 10장에 5만원)",
    review: "https://maps.app.goo.gl/PrGY81XhSB8GCPYY6",
  },
  {
    name: "밥먹은 닭",
    glyphicons: "bi-star",
    tags: "계란덮밥, 치킨덮밥, 제육덮밥, 떡만두국, 냉모밀",
  },
  {
    name: "판교 상록면",
    glyphicons: "bi-star",
    tags: "우동, 소바, 닭고기 덮밥",
  },
  {
    name: "판교 차이나 오라",
    glyphicons: "bi-star",
    tags: "짜장면, 짱뽕",
  },
  {
    name: "판교 락앤웍",
    glyphicons: "bi-star",
    tags: "짜장면, 짱뽕",
  },
  {
    name: "판교 찌개애",
    glyphicons: "bi-star",
    tags: "된장찌개, 생선구이",
  },
  {
    name: "킹콩 부대 찌개",
    glyphicons: "bi-star",
    tags: "킹콩 부대찌개",
  },
  {
    name: "판교 진진반상",
    glyphicons: "bi-star",
    tags: "진진반상(한식)",
  },
  {
    name: "판교 더 집밥",
    glyphicons: "bi-star",
    tags: "백반",
  },
  {
    name: "판교 서경 백반집",
    glyphicons: "bi-star",
    tags: "백반",
  },
  {
    name: "판교 집밥맛있다",
    glyphicons: "bi-star",
    tags: "집밥",
  },
  {
    name: "소호정",
    glyphicons: "bi-star",
    tags: "집밥",
  },
  {
    name: "판교 상황 삼계탕",
    glyphicons: "bi-star",
    tags: "삼계탕, 닭도리탕",
  },
  {
    name: "판교 정원 오리부추 구이",
    glyphicons: "bi-star",
    tags: "오리구이,볶음밥",
  },
  {
    name: "판교 명인 만두",
    glyphicons: "bi-heart",
    tags: "비빔밤, 라면, 만두, 돈까스, 오므라이스, 기타 분식",
  },
  {
    name: "판교 강남 교자",
    glyphicons: "bi-star",
    tags: "만두국, 칼국수",
  },
  {
    name: "판교 군산 오징어",
    glyphicons: "bi-star",
    tags: "오징어 불고기",
  },
  {
    name: "판교 오징어랑",
    glyphicons: "bi-star",
    tags: "오징어 볶음, 고등어 구이",
  },
  {
    name: "판교 마키노 차야",
    glyphicons: "bi-star",
    tags: "씨푸드 뷔페",
  },
  {
    name: "매드 포 갈릭",
    glyphicons: "bi-star",
    tags: "갈릭 피자, 파스타, 스테이크",
  },
  {
    name: "순남 시래기",
    glyphicons: "bi-star",
    tags: "시래기국, 반찬 셀프",
  },
  {
    name: "판교 모모 카페",
    glyphicons: "bi-star",
    tags: "뷔페",
  },
  {
    name: "판교 짱가네 포크포크",
    glyphicons: "bi-star",
    tags: "냉면 돈까스",
  },
  {
    name: "판교 됐소",
    glyphicons: "bi-star",
    tags: "차돌된장찌개(점심시간만),김치째게(점심시간만)",
  },
  {
    name: "판교 담소사골순대",
    glyphicons: "bi-star",
    tags: "순대국밥",
  },
  {
    name: "판교 차이엔",
    glyphicons: "bi-star",
    tags: "짜장면, 짱뽕, 탕수육, 깐풍기, 누룽지탕",
  },
  {
    name: "빽다방",
    glyphicons: "bi-star",
    tags: "커피, 사라다빵, 딸바쥬스, 초코쥬스",
  },
  {
    name: "판교 더 피크닉",
    glyphicons: "bi-star",
    tags: "오므라이스, 오믈렛, 리코타치즈 샐러드",
  },
  {
    name: "판교 기름 짜는 김밥집",
    glyphicons: "bi-star",
    tags: "김밥, 쫄면, 분식",
  },
  {
    name: "반장 떡볶이",
    glyphicons: "bi-star",
    tags: "반장떡볶이, 부반장떡볶이, 전학생떡볶이",
  },
  {
    name: "오군 식당",
    glyphicons: "bi-star",
    tags: "오군 카레",
  },
  {
    name: "판교 브랜든 돈까스",
    glyphicons: "bi-star",
    tags: "돈까스, 치킨까스, 생선까스",
  },
  {
    name: "판교 서호 돈까스",
    glyphicons: "bi-star",
    tags: "돈까스",
  },
  {
    name: "샤보텐",
    glyphicons: "bi-star",
    tags: "돈까스, 치킨까스, 우동",
  },
  {
    name: "생어거스틴",
    glyphicons: "bi-star",
    tags: "팟타이, 나시고랭, 파인애플 볶음밥",
  },
  {
    name: "아세야마",
    glyphicons: "bi-star",
    tags: "덴푸라 카레, 가아라게 카레",
  },
  {
    name: "채선당 플러스",
    glyphicons: "bi-star",
    tags: "샤브샤브, 뷔페",
  },
  {
    name: "맥도날드",
    glyphicons: "bi-star",
    tags: "버거, 감자튀김, 아이스크림, 쉐이크",
  },
  {
    name: "버거킹",
    glyphicons: "bi-star",
    tags: "버거, 감자튀김",
  },
  {
    name: "판교 찬장",
    glyphicons: "bi-star",
    tags: "고등어 구이, 순두부찌개",
  },
  {
    name: "더 냄비",
    glyphicons: "bi-star",
    tags: "닭고기 정식, 쭈꾸미, 제육볶음",
  },
  {
    name: "판교 준영",
    glyphicons: "bi-heart",
    tags: "파이탄라멘, 매운라멘, 차슈동",
    review: "https://maps.app.goo.gl/EQ8nfS3NJCsvhLb38",
  },
  {
    name: "다루마 라멘",
    glyphicons: "bi-star",
    tags: "돈코츠 라멘, 쯔께멘",
  },
  {
    name: "두부가 보쌈애",
    glyphicons: "bi-star",
    tags: "두부 김치짹, 해물 된장찌개",
  },
  {
    name: "홍대 돈부리",
    glyphicons: "bi-star",
    tags: "새우튀김우동, 믹스가츠동, 사케우나기동",
  },
  {
    name: "판교 카레 뜰에",
    glyphicons: "bi-star",
    tags: "돈까스 카레, 치킨까스 카레",
  },
  {
    name: "김밥 천국",
    glyphicons: "bi-star",
    tags: "김밥, 떡볶이, 기타 분식",
  },
  {
    name: "판교 미쓰 싸이공",
    glyphicons: "bi-star",
    tags: "소고기 쌀국수, 사이공 볶음밥",
  },
  {
    name: "판교 낭 싸이공",
    glyphicons: "bi-star",
    tags: "쌀국수, 볶음밥",
  },
  {
    name: "판교 전주 콩나물 국밥",
    glyphicons: "bi-star",
    tags: "김치찌개, 제육볶음, 김치찜",
    review: "https://maps.app.goo.gl/TDDmBMZLyuBbe2gn8",
  },
  {
    name: "판교 죠샌드위치",
    glyphicons: "bi-star",
    tags: "샌드위치",
  },
  {
    name: "메콩타이",
    glyphicons: "bi-star",
    tags: "소고기 쌀국수, 파인애플 볶음밥",
  },
  {
    name: "판교 슈퍼타이",
    glyphicons: "bi-star",
    tags: "소고기 쌀국수, 파인애플 볶음밥",
  },
  {
    name: "포메인",
    glyphicons: "bi-star",
    tags: "쌀국수, 볶음밥",
  },
  {
    name: "판교 샐러드박스",
    glyphicons: "bi-heart",
    tags: "다이어트, 샐러드",
    review: "https://maps.app.goo.gl/GCobvQCuAZbSKes68",
  },
  {
    name: "써브웨이",
    glyphicons: "bi-heart",
    tags: "샌드위치, 샐러드",
  },
  {
    name: "봉편메밀촌 뜨락",
    glyphicons: "bi-star",
    tags: "비빔막국수, 메밀소바, 메밀칼국수",
  },
  {
    name: "판교 광남 포차",
    glyphicons: "bi-star",
    tags: "떡볶이, 순대, 돈까스, 라면",
  },
  {
    name: "판교 영심이 떡볶이",
    glyphicons: "bi-star",
    tags: "떡볶이, 순대",
  },
  {
    name: "판교 나고미",
    glyphicons: "bi-star",
    tags: "카레 돈부리, 제육덮밥, 참치덮밥",
  },
  {
    name: "판교 밥볶다",
    glyphicons: "bi-star",
    tags: "불고기 밴반 볶음",
  },
  {
    name: "판교 오덮",
    glyphicons: "bi-star",
    tags: "오징어덮밥, 제육덮밥, 참치덮밥",
  },
  {
    name: "판교 스시쿤",
    glyphicons: "bi-star",
    tags: "스시",
  },
  {
    name: "판교 림꼬또",
    glyphicons: "bi-x-circle",
    tags: "치킨 덮밥, 소고기 덮밥",
  },
  {
    name: "판교 등심촌",
    glyphicons: "bi-x-circle",
    tags: "밀면 (고무줄)",
  },
  {
    name: "판교 챠오바라이트",
    glyphicons: "bi-x-circle",
    tags: "파스타 (서비스,음식 엉망)",
  },
];
