name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 배포하려는 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # vite.config.js > __MYENV_READONLY_TOKEN__ 환경변수 설정을 위해 settings > secrets and variables > actions > secrets 로 추가했다.
      myenv_readonly_token: ${{ secrets.MYENV_READONLY_TOKEN_SECRET }}
      variable_test: ${{ vars.TEST1 }}
    steps:
      - uses: actions/checkout@v4
      # https://bun.sh/guides/runtime/cicd
      - uses: oven-sh/setup-bun@v2

      - name: for test
        run: |
          echo "myenv_readonly_token:$myenv_readonly_token"
          echo "variable_test       :$variable_test"
          curl -L https://api.github.com/repos/ysoftman/myenv/contents/nvim/lua/plugins \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $myenv_readonly_token"

      - name: Build
        run: |
          bun install
          bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 빌드 결과물이 있는 디렉토리

